import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :neon_compliance, NeonComplianceWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: NeonCompliance.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Use JSON formatter for production logs (for log aggregation)
config :logger, :console,
  format: {NeonComplianceWeb.Loggers.JSONFormatter, :format}

# Production database pool size (overridden by runtime.exs if POOL_SIZE env var set)
# Recommended: (avg_query_time_ms / 1000) * req_per_second * safety_factor
# Example: (200ms / 1000) * 100 req/s * 1.5 = 30 connections
config :neon_compliance, NeonCompliance.Repo,
  pool_size: 20,
  queue_target: 50,
  queue_interval: 1000,
  timeout: 15_000

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
